[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "valmix"
readme = "README.md"
authors = [
    {name = "Stéphane Caron", email = "stephane.caron@inria.fr"},
]
maintainers = [
    {name = "Stéphane Caron", email = "stephane.caron@inria.fr"},
]
dynamic = ['version', 'description']
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Typing :: Typed",
]
dependencies = [
    "textual >=0.57.1",
]
keywords = ["multiprocessing", "value", "tui", "user", "interface"]

[project.urls]
Source = "https://github.com/stephane-caron/valmix"
Tracker = "https://github.com/stephane-caron/valmix/issues"
Changelog = "https://github.com/stephane-caron/valmix/blob/main/CHANGELOG.md"

[tool.black]
line-length = 79

[tool.flit.module]
name = "valmix"

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = [
    # pyflakes
    "F",
    # pycodestyle
    "E",
    "W",
    # isort
    "I001",
    # pydocstyle
    "D"
]
ignore = [
    "D401",  # good for methods but not for class docstrings
    "D405",  # British-style section names are also "proper"!
]

[tool.ruff.lint.pydocstyle]
convention = "google"
